// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9IjJFTuUwDgzgJgRKl_eio5VMRTNZ8Y',
    appId: '1:341051907713:web:f4c04cf7cbf8620c65b780',
    messagingSenderId: '341051907713',
    projectId: 'hackathon-dcd8f',
    authDomain: 'hackathon-dcd8f.firebaseapp.com',
    databaseURL: 'https://hackathon-dcd8f-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-dcd8f.firebasestorage.app',
    measurementId: 'G-J8KY26488K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDchQ0jIyt6ydIZtdXGOnmuiyL2B5kc2vw',
    appId: '1:341051907713:android:05e25021f4a3eb0365b780',
    messagingSenderId: '341051907713',
    projectId: 'hackathon-dcd8f',
    databaseURL: 'https://hackathon-dcd8f-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-dcd8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcjhsu2f80Q8ywbp79Gtwy33MC80MvZw',
    appId: '1:341051907713:ios:50fb0521d81889b265b780',
    messagingSenderId: '341051907713',
    projectId: 'hackathon-dcd8f',
    databaseURL: 'https://hackathon-dcd8f-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-dcd8f.firebasestorage.app',
    iosClientId: '341051907713-dm3mgblj1saoq43evuhnr465gogefdr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackutd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcjhsu2f80Q8ywbp79Gtwy33MC80MvZw',
    appId: '1:341051907713:ios:50fb0521d81889b265b780',
    messagingSenderId: '341051907713',
    projectId: 'hackathon-dcd8f',
    databaseURL: 'https://hackathon-dcd8f-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-dcd8f.firebasestorage.app',
    iosClientId: '341051907713-dm3mgblj1saoq43evuhnr465gogefdr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackutd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx9IjJFTuUwDgzgJgRKl_eio5VMRTNZ8Y',
    appId: '1:341051907713:web:552967a3c6bec52465b780',
    messagingSenderId: '341051907713',
    projectId: 'hackathon-dcd8f',
    authDomain: 'hackathon-dcd8f.firebaseapp.com',
    databaseURL: 'https://hackathon-dcd8f-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-dcd8f.firebasestorage.app',
    measurementId: 'G-F1HCVJFTWS',
  );
}
